name: BrettBorders
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4c4d4f'
    - '#d88637'
    - '#676869'
    - '#9a9a9c'
  brandStrength: 0.75
  lightness: 0.7608892663847655
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
