name: BrettBorders
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2967937462963164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfb'
    - '#e06637'
    - '#e7d5af'
    - '#4f3620'
    - '#e7b441'
  brandStrength: 0.23083388130180538
  lightness: 0.7608892663847655
  saturation: 0.721180765889585
  rhythmicContrast: 0.015272386837750673
purpose: []
